const API_URL = "https://findalleasy-ai-search-handler.onrender.com";
const LOCALES=['tr','en','de','fr','es','ru','ar','jp'];

function detectLang(){const nav=(navigator.language||'en').toLowerCase();for(const l of LOCALES){if(nav.startsWith(l)) return l;}return 'en';}
async function loadLocale(lang){const res=await fetch(`lang/${lang}.json`);return await res.json();}
function greetingByTime(pack){const h=new Date().getHours();if(h>=5&&h<11)return pack.ai_headline_morning;if(h>=11&&h<17)return pack.ai_headline_day;if(h>=17&&h<22)return pack.ai_headline_evening;return pack.ai_headline_night;}
function rotatePlaceholder(items){let i=0;const input=document.getElementById('searchInput');input.placeholder=items[i%items.length];setInterval(()=>{i++;input.placeholder=items[i%items.length];},2500);}
function fillLangSelect(current){const sel=document.getElementById('langSelect');LOCALES.forEach(code=>{const opt=document.createElement('option');opt.value=code;opt.textContent=code.toUpperCase();if(code===current)opt.selected=true;sel.appendChild(opt);});sel.addEventListener('change',async e=>{const lang=e.target.value;localStorage.setItem('fae_lang',lang);await applyLang(lang);});}
async function applyLang(lang){const pack=await loadLocale(lang);document.documentElement.lang=lang;document.getElementById('slogan').innerHTML=pack.slogan_html;document.getElementById('aiHeadline').textContent=pack.trends;document.getElementById('aiGreeting').textContent=greetingByTime(pack);document.getElementById('aboutTitle').textContent=pack.about_title;document.getElementById('aboutText').textContent=pack.about_text;document.getElementById('searchBtn').textContent=pack.search;rotatePlaceholder(pack.placeholder_items);}
async function init(){const saved=localStorage.getItem('fae_lang');const lang=saved||detectLang();fillLangSelect(lang);await applyLang(lang);document.getElementById('voiceBtn').addEventListener('click',async()=>{const transcript=prompt('Konuşma metnini gir (demo):');if(!transcript)return;const fd=new FormData();fd.append('transcript',transcript);fd.append('ui_lang',lang);try{const res=await fetch(`${API_URL}/voice`,{method:'POST',body:fd});const data=await res.json();document.getElementById('searchInput').value=data.preview||transcript;}catch(e){console.warn(e);}});document.getElementById('imageInput').addEventListener('change',async ev=>{const file=ev.target.files[0];if(!file)return;const fd=new FormData();fd.append('file',file);fd.append('ui_lang',lang);try{const res=await fetch(`${API_URL}/vision`,{method:'POST',body:fd});const data=await res.json();document.getElementById('searchInput').value=data.preview||'';}catch(e){console.warn(e);}});document.getElementById('searchBtn').addEventListener('click',()=>runSearch(lang));document.querySelectorAll('.card').forEach(card=>{card.addEventListener('click',()=>{const v=card.dataset.cat||'';document.getElementById('searchInput').value=v;runSearch(lang);});});}
async function runSearch(lang){const q=document.getElementById('searchInput').value.trim();if(!q)return;const url=`${API_URL}/search?q=${encodeURIComponent(q)}&category=Genel&region=GLOBAL`;try{const res=await fetch(url);const data=await res.json();renderResults(data.results||[]);}catch(e){console.warn(e);}}
function renderResults(items){const area=document.querySelector('.showcase');area.innerHTML='';(items.slice(0,4)).forEach(it=>{const div=document.createElement('div');div.className='card';div.innerHTML=`<div style="padding:12px 12px 0 12px"><div style="font-weight:600;color:#E5D3B3;margin-bottom:6px">${it.title}</div></div><div style="padding:0 12px 12px 12px;color:#F5F5F0"><div>Seller: ${it.seller} • Source: ${it.source}</div><div style="margin-top:6px">List: ${it.price} • <b>FindAllEasy: ${it.findalleasy_price}</b></div><a href="${it.link}" target="_blank" style="display:inline-block;margin-top:8px;color:#0078FF">Go</a></div>`;area.appendChild(div);});}
init();